/**
 * CID-10 PT-BR data for autocomplete.
 * Source: DATASUS / OMS CID-10 - Classificação Internacional de Doenças (10ª revisão)
 * Contains the most commonly used codes in Brazilian clinical practice.
 */

export interface CID10Code {
  code: string;
  name: string;
}

// Remove diacritics for search normalization
function removeDiacritics(str: string): string {
  return str.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}

// Normalize for search: lowercase + no diacritics
function normalizeForSearch(str: string): string {
  return removeDiacritics(str.toLowerCase());
}

const CID10_DATABASE: CID10Code[] = [
  // ===== A00-B99: Doenças infecciosas e parasitárias =====
  { code: 'A00', name: 'Cólera' },
  { code: 'A01', name: 'Febres tifóide e paratifóide' },
  { code: 'A02', name: 'Outras infecções por Salmonella' },
  { code: 'A04', name: 'Outras infecções intestinais bacterianas' },
  { code: 'A05', name: 'Outras intoxicações alimentares bacterianas' },
  { code: 'A06', name: 'Amebíase' },
  { code: 'A09', name: 'Diarréia e gastroenterite de origem infecciosa presumível' },
  { code: 'A15', name: 'Tuberculose respiratória, com confirmação bacteriológica e histológica' },
  { code: 'A16', name: 'Tuberculose das vias respiratórias, sem confirmação bacteriológica ou histológica' },
  { code: 'A20', name: 'Peste' },
  { code: 'A21', name: 'Tularemia' },
  { code: 'A23', name: 'Brucelose' },
  { code: 'A27', name: 'Leptospirose' },
  { code: 'A30', name: 'Hanseníase (doença de Hansen)' },
  { code: 'A33', name: 'Tétano do recém-nascido' },
  { code: 'A34', name: 'Tétano obstétrico' },
  { code: 'A35', name: 'Outros tipos de tétano' },
  { code: 'A36', name: 'Difteria' },
  { code: 'A37', name: 'Coqueluche' },
  { code: 'A38', name: 'Escarlatina' },
  { code: 'A39', name: 'Infecção meningocócica' },
  { code: 'A40', name: 'Septicemia estreptocócica' },
  { code: 'A41', name: 'Outras septicemias' },
  { code: 'A41.9', name: 'Septicemia não especificada' },
  { code: 'A46', name: 'Erisipela' },
  { code: 'A49', name: 'Infecção bacteriana de localização não especificada' },
  { code: 'A50', name: 'Sífilis congênita' },
  { code: 'A51', name: 'Sífilis precoce' },
  { code: 'A52', name: 'Sífilis tardia' },
  { code: 'A53', name: 'Outras formas e as não especificadas da sífilis' },
  { code: 'A54', name: 'Infecção gonocócica' },
  { code: 'A56', name: 'Outras doenças sexualmente transmitidas por clamídias' },
  { code: 'A59', name: 'Tricomoníase' },
  { code: 'A60', name: 'Infecção anogenital pelo vírus do herpes' },
  { code: 'A63', name: 'Outras doenças de transmissão predominantemente sexual' },
  { code: 'A69', name: 'Outras infecções por espiroquetas' },
  { code: 'A70', name: 'Infecção por Chlamydia psittaci' },
  { code: 'A71', name: 'Tracoma' },
  { code: 'A77', name: 'Febre maculosa (rickettsioses transmitidas por carrapatos)' },
  { code: 'A80', name: 'Poliomielite aguda' },
  { code: 'A82', name: 'Raiva' },
  { code: 'A84', name: 'Encefalite por vírus transmitido por carrapatos' },
  { code: 'A90', name: 'Dengue (dengue clássico)' },
  { code: 'A91', name: 'Febre hemorrágica devida ao vírus do dengue' },
  { code: 'A92.0', name: 'Febre de Chikungunya' },
  { code: 'A92.8', name: 'Febre pelo vírus Zika' },
  { code: 'A95', name: 'Febre amarela' },
  { code: 'A96', name: 'Febre hemorrágica por arenavírus' },
  { code: 'B00', name: 'Infecções pelo vírus do herpes (herpes simples)' },
  { code: 'B01', name: 'Varicela (catapora)' },
  { code: 'B02', name: 'Herpes zoster (zona)' },
  { code: 'B05', name: 'Sarampo' },
  { code: 'B06', name: 'Rubéola' },
  { code: 'B07', name: 'Verrugas de origem viral' },
  { code: 'B08', name: 'Outras infecções virais com lesões de pele e mucosas' },
  { code: 'B09', name: 'Infecção viral não especificada com lesões de pele e mucosas' },
  { code: 'B15', name: 'Hepatite aguda A' },
  { code: 'B16', name: 'Hepatite aguda B' },
  { code: 'B17', name: 'Outras hepatites virais agudas' },
  { code: 'B18', name: 'Hepatite viral crônica' },
  { code: 'B18.1', name: 'Hepatite viral crônica B sem agente delta' },
  { code: 'B18.2', name: 'Hepatite viral crônica C' },
  { code: 'B19', name: 'Hepatite viral não especificada' },
  { code: 'B20', name: 'Doença pelo HIV resultando em doenças infecciosas e parasitárias' },
  { code: 'B24', name: 'Doença pelo vírus da imunodeficiência humana (HIV) não especificada' },
  { code: 'B25', name: 'Doença por citomegalovírus' },
  { code: 'B26', name: 'Caxumba (parotidite epidêmica)' },
  { code: 'B27', name: 'Mononucleose infecciosa' },
  { code: 'B30', name: 'Conjuntivite viral' },
  { code: 'B34', name: 'Infecção viral de localização não especificada' },
  { code: 'B34.9', name: 'Infecção viral não especificada' },
  { code: 'B35', name: 'Dermatofitose (tinha)' },
  { code: 'B36', name: 'Outras micoses superficiais' },
  { code: 'B37', name: 'Candidíase' },
  { code: 'B37.0', name: 'Estomatite por Candida' },
  { code: 'B37.3', name: 'Candidíase da vulva e da vagina' },
  { code: 'B44', name: 'Aspergilose' },
  { code: 'B45', name: 'Criptococose' },
  { code: 'B50', name: 'Malária por Plasmodium falciparum' },
  { code: 'B51', name: 'Malária por Plasmodium vivax' },
  { code: 'B54', name: 'Malária não especificada' },
  { code: 'B55', name: 'Leishmaniose' },
  { code: 'B57', name: 'Doença de Chagas' },
  { code: 'B58', name: 'Toxoplasmose' },
  { code: 'B65', name: 'Esquistossomose (bilharziose)' },
  { code: 'B68', name: 'Teníase' },
  { code: 'B69', name: 'Cisticercose' },
  { code: 'B73', name: 'Oncocercose' },
  { code: 'B76', name: 'Ancilostomíase' },
  { code: 'B77', name: 'Ascaridíase' },
  { code: 'B80', name: 'Oxiuríase' },
  { code: 'B82', name: 'Parasitose intestinal não especificada' },
  { code: 'B83', name: 'Outras helmintíases' },
  { code: 'B86', name: 'Escabiose (sarna)' },
  { code: 'B87', name: 'Miíase' },

  // ===== C00-D48: Neoplasias =====
  { code: 'C00', name: 'Neoplasia maligna do lábio' },
  { code: 'C01', name: 'Neoplasia maligna da base da língua' },
  { code: 'C06', name: 'Neoplasia maligna de outras partes e de partes não especificadas da boca' },
  { code: 'C09', name: 'Neoplasia maligna da amígdala' },
  { code: 'C10', name: 'Neoplasia maligna da orofaringe' },
  { code: 'C15', name: 'Neoplasia maligna do esôfago' },
  { code: 'C16', name: 'Neoplasia maligna do estômago' },
  { code: 'C17', name: 'Neoplasia maligna do intestino delgado' },
  { code: 'C18', name: 'Neoplasia maligna do cólon' },
  { code: 'C19', name: 'Neoplasia maligna da junção retossigmóide' },
  { code: 'C20', name: 'Neoplasia maligna do reto' },
  { code: 'C22', name: 'Neoplasia maligna do fígado e das vias biliares intra-hepáticas' },
  { code: 'C23', name: 'Neoplasia maligna da vesícula biliar' },
  { code: 'C25', name: 'Neoplasia maligna do pâncreas' },
  { code: 'C32', name: 'Neoplasia maligna da laringe' },
  { code: 'C33', name: 'Neoplasia maligna da traquéia' },
  { code: 'C34', name: 'Neoplasia maligna dos brônquios e dos pulmões' },
  { code: 'C43', name: 'Melanoma maligno da pele' },
  { code: 'C44', name: 'Outras neoplasias malignas da pele' },
  { code: 'C50', name: 'Neoplasia maligna da mama' },
  { code: 'C53', name: 'Neoplasia maligna do colo do útero' },
  { code: 'C54', name: 'Neoplasia maligna do corpo do útero' },
  { code: 'C55', name: 'Neoplasia maligna do útero, porção não especificada' },
  { code: 'C56', name: 'Neoplasia maligna do ovário' },
  { code: 'C61', name: 'Neoplasia maligna da próstata' },
  { code: 'C62', name: 'Neoplasia maligna dos testículos' },
  { code: 'C64', name: 'Neoplasia maligna do rim, exceto pelve renal' },
  { code: 'C67', name: 'Neoplasia maligna da bexiga' },
  { code: 'C71', name: 'Neoplasia maligna do encéfalo' },
  { code: 'C73', name: 'Neoplasia maligna da glândula tireóide' },
  { code: 'C76', name: 'Neoplasia maligna de outras localizações e de localizações mal definidas' },
  { code: 'C77', name: 'Neoplasia maligna secundária e não especificada dos gânglios linfáticos' },
  { code: 'C78', name: 'Neoplasia maligna secundária dos órgãos respiratórios e digestivos' },
  { code: 'C79', name: 'Neoplasia maligna secundária de outras localizações' },
  { code: 'C80', name: 'Neoplasia maligna sem especificação de localização' },
  { code: 'C81', name: 'Doença de Hodgkin (linfoma de Hodgkin)' },
  { code: 'C82', name: 'Linfoma não-Hodgkin folicular (nodular)' },
  { code: 'C83', name: 'Linfoma não-Hodgkin difuso' },
  { code: 'C85', name: 'Linfoma não-Hodgkin de outros tipos e de tipo não especificado' },
  { code: 'C90', name: 'Mieloma múltiplo e neoplasias malignas de plasmócitos' },
  { code: 'C91', name: 'Leucemia linfóide' },
  { code: 'C92', name: 'Leucemia mielóide' },
  { code: 'C95', name: 'Leucemia de tipo celular não especificado' },
  { code: 'D06', name: 'Carcinoma in situ do colo do útero' },
  { code: 'D10', name: 'Neoplasia benigna da boca e da faringe' },
  { code: 'D12', name: 'Neoplasia benigna do cólon, reto, canal anal e ânus' },
  { code: 'D13', name: 'Neoplasia benigna de outras partes e de partes mal definidas do aparelho digestivo' },
  { code: 'D17', name: 'Neoplasia lipomatosa benigna (lipoma)' },
  { code: 'D22', name: 'Nevos melanocíticos' },
  { code: 'D24', name: 'Neoplasia benigna da mama' },
  { code: 'D25', name: 'Leiomioma do útero (mioma uterino)' },
  { code: 'D27', name: 'Neoplasia benigna do ovário' },
  { code: 'D32', name: 'Neoplasia benigna das meninges' },
  { code: 'D34', name: 'Neoplasia benigna da glândula tireóide' },
  { code: 'D35', name: 'Neoplasia benigna de outras glândulas endócrinas e das não especificadas' },

  // ===== D50-D89: Doenças do sangue =====
  { code: 'D50', name: 'Anemia por deficiência de ferro' },
  { code: 'D50.0', name: 'Anemia por deficiência de ferro secundária a perda de sangue (crônica)' },
  { code: 'D50.9', name: 'Anemia por deficiência de ferro não especificada' },
  { code: 'D51', name: 'Anemia por deficiência de vitamina B12' },
  { code: 'D52', name: 'Anemia por deficiência de folato' },
  { code: 'D53', name: 'Outras anemias nutricionais' },
  { code: 'D56', name: 'Talassemia' },
  { code: 'D57', name: 'Anemia falciforme' },
  { code: 'D58', name: 'Outras anemias hemolíticas hereditárias' },
  { code: 'D59', name: 'Anemia hemolítica adquirida' },
  { code: 'D61', name: 'Outras anemias aplásticas' },
  { code: 'D64', name: 'Outras anemias' },
  { code: 'D64.9', name: 'Anemia não especificada' },
  { code: 'D65', name: 'Coagulação intravascular disseminada' },
  { code: 'D66', name: 'Deficiência hereditária do fator VIII (hemofilia A)' },
  { code: 'D68', name: 'Outros defeitos da coagulação' },
  { code: 'D69', name: 'Púrpura e outras afecções hemorrágicas' },
  { code: 'D69.3', name: 'Púrpura trombocitopênica idiopática' },
  { code: 'D69.6', name: 'Trombocitopenia não especificada' },
  { code: 'D70', name: 'Agranulocitose (neutropenia)' },
  { code: 'D72', name: 'Outros transtornos dos glóbulos brancos' },
  { code: 'D80', name: 'Imunodeficiência com predominância de defeitos de anticorpos' },
  { code: 'D83', name: 'Imunodeficiência comum variável' },
  { code: 'D84', name: 'Outras imunodeficiências' },
  { code: 'D89', name: 'Outros transtornos do sistema imunitário' },

  // ===== E00-E90: Doenças endócrinas, nutricionais e metabólicas =====
  { code: 'E00', name: 'Síndrome de deficiência congênita de iodo' },
  { code: 'E01', name: 'Transtornos tireoidianos e afecções associadas, relacionados à deficiência de iodo' },
  { code: 'E03', name: 'Outros hipotireoidismos' },
  { code: 'E03.9', name: 'Hipotireoidismo não especificado' },
  { code: 'E04', name: 'Outros bócios não-tóxicos' },
  { code: 'E04.1', name: 'Nódulo tireoidiano solitário não-tóxico' },
  { code: 'E04.2', name: 'Bócio multinodular não-tóxico' },
  { code: 'E05', name: 'Tireotoxicose (hipertireoidismo)' },
  { code: 'E05.0', name: 'Tireotoxicose com bócio difuso (doença de Graves)' },
  { code: 'E06', name: 'Tireoidite' },
  { code: 'E06.3', name: 'Tireoidite auto-imune (tireoidite de Hashimoto)' },
  { code: 'E07', name: 'Outros transtornos da tireóide' },
  { code: 'E10', name: 'Diabetes mellitus insulino-dependente (tipo 1)' },
  { code: 'E10.0', name: 'Diabetes mellitus tipo 1 com coma' },
  { code: 'E10.1', name: 'Diabetes mellitus tipo 1 com cetoacidose' },
  { code: 'E10.2', name: 'Diabetes mellitus tipo 1 com complicações renais' },
  { code: 'E10.3', name: 'Diabetes mellitus tipo 1 com complicações oftálmicas' },
  { code: 'E10.4', name: 'Diabetes mellitus tipo 1 com complicações neurológicas' },
  { code: 'E10.5', name: 'Diabetes mellitus tipo 1 com complicações circulatórias periféricas' },
  { code: 'E10.9', name: 'Diabetes mellitus tipo 1 sem complicações' },
  { code: 'E11', name: 'Diabetes mellitus não-insulino-dependente (tipo 2)' },
  { code: 'E11.0', name: 'Diabetes mellitus tipo 2 com coma' },
  { code: 'E11.1', name: 'Diabetes mellitus tipo 2 com cetoacidose' },
  { code: 'E11.2', name: 'Diabetes mellitus tipo 2 com complicações renais' },
  { code: 'E11.3', name: 'Diabetes mellitus tipo 2 com complicações oftálmicas' },
  { code: 'E11.4', name: 'Diabetes mellitus tipo 2 com complicações neurológicas' },
  { code: 'E11.5', name: 'Diabetes mellitus tipo 2 com complicações circulatórias periféricas' },
  { code: 'E11.7', name: 'Diabetes mellitus tipo 2 com complicações múltiplas' },
  { code: 'E11.9', name: 'Diabetes mellitus tipo 2 sem complicações' },
  { code: 'E13', name: 'Outros tipos especificados de diabetes mellitus' },
  { code: 'E14', name: 'Diabetes mellitus não especificado' },
  { code: 'E16', name: 'Outros transtornos da secreção interna do pâncreas' },
  { code: 'E20', name: 'Hipoparatireoidismo' },
  { code: 'E21', name: 'Hiperparatireoidismo e outros transtornos da glândula paratireóide' },
  { code: 'E22', name: 'Hiperfunção da hipófise' },
  { code: 'E23', name: 'Hipofunção e outros transtornos da hipófise' },
  { code: 'E24', name: 'Síndrome de Cushing' },
  { code: 'E25', name: 'Transtornos adrenogenitais' },
  { code: 'E27', name: 'Outros transtornos da glândula supra-renal' },
  { code: 'E27.1', name: 'Insuficiência adrenocortical primária (doença de Addison)' },
  { code: 'E28', name: 'Disfunção ovariana' },
  { code: 'E29', name: 'Disfunção testicular' },
  { code: 'E34', name: 'Outros transtornos endócrinos' },
  { code: 'E40', name: 'Kwashiorkor' },
  { code: 'E41', name: 'Marasmo nutricional' },
  { code: 'E43', name: 'Desnutrição protéico-calórica grave não especificada' },
  { code: 'E44', name: 'Desnutrição protéico-calórica de graus moderado e leve' },
  { code: 'E46', name: 'Desnutrição protéico-calórica não especificada' },
  { code: 'E50', name: 'Deficiência de vitamina A' },
  { code: 'E53', name: 'Deficiência de outras vitaminas do grupo B' },
  { code: 'E55', name: 'Deficiência de vitamina D' },
  { code: 'E55.0', name: 'Raquitismo ativo' },
  { code: 'E55.9', name: 'Deficiência não especificada de vitamina D' },
  { code: 'E56', name: 'Outras deficiências vitamínicas' },
  { code: 'E58', name: 'Deficiência de cálcio na dieta' },
  { code: 'E61', name: 'Deficiência de outros elementos nutrientes' },
  { code: 'E61.1', name: 'Deficiência de ferro' },
  { code: 'E63', name: 'Outras deficiências nutricionais' },
  { code: 'E65', name: 'Obesidade e hiperalimentação' },
  { code: 'E66', name: 'Obesidade' },
  { code: 'E66.0', name: 'Obesidade devida a excesso de calorias' },
  { code: 'E66.9', name: 'Obesidade não especificada' },
  { code: 'E67', name: 'Outras formas de hiperalimentação' },
  { code: 'E70', name: 'Distúrbios do metabolismo de aminoácidos aromáticos' },
  { code: 'E72', name: 'Outros distúrbios do metabolismo de aminoácidos' },
  { code: 'E73', name: 'Intolerância à lactose' },
  { code: 'E78', name: 'Distúrbios do metabolismo de lipoproteínas e outras lipidemias' },
  { code: 'E78.0', name: 'Hipercolesterolemia pura' },
  { code: 'E78.1', name: 'Hipertrigliceridemia pura' },
  { code: 'E78.2', name: 'Hiperlipidemia mista' },
  { code: 'E78.5', name: 'Hiperlipidemia não especificada' },
  { code: 'E79', name: 'Distúrbios do metabolismo de purinas e pirimidinas' },
  { code: 'E79.0', name: 'Hiperuricemia sem sinais de artrite inflamatória e de doença tofácea' },
  { code: 'E83', name: 'Distúrbios do metabolismo de minerais' },
  { code: 'E84', name: 'Fibrose cística (mucoviscidose)' },
  { code: 'E86', name: 'Depleção de volume (desidratação)' },
  { code: 'E87', name: 'Outros transtornos do equilíbrio hidroeletrolítico e ácido-básico' },
  { code: 'E87.1', name: 'Hiponatremia' },
  { code: 'E87.6', name: 'Hipopotassemia' },
  { code: 'E88', name: 'Outros distúrbios metabólicos' },
  { code: 'E89', name: 'Transtornos endócrinos e metabólicos pós-procedimentos' },
  { code: 'E90', name: 'Transtornos nutricionais e metabólicos em doenças classificadas em outra parte' },

  // ===== F00-F99: Transtornos mentais e comportamentais =====
  { code: 'F00', name: 'Demência na doença de Alzheimer' },
  { code: 'F01', name: 'Demência vascular' },
  { code: 'F02', name: 'Demência em outras doenças classificadas em outra parte' },
  { code: 'F03', name: 'Demência não especificada' },
  { code: 'F05', name: 'Delirium não induzido pelo álcool ou por outras substâncias psicoativas' },
  { code: 'F06', name: 'Outros transtornos mentais devidos a lesão e disfunção cerebral e a doença física' },
  { code: 'F10', name: 'Transtornos mentais e comportamentais devidos ao uso de álcool' },
  { code: 'F10.0', name: 'Intoxicação aguda por álcool' },
  { code: 'F10.1', name: 'Uso nocivo de álcool' },
  { code: 'F10.2', name: 'Síndrome de dependência de álcool' },
  { code: 'F10.3', name: 'Estado de abstinência de álcool' },
  { code: 'F11', name: 'Transtornos mentais e comportamentais devidos ao uso de opiáceos' },
  { code: 'F12', name: 'Transtornos mentais e comportamentais devidos ao uso de canabinóides' },
  { code: 'F13', name: 'Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos' },
  { code: 'F14', name: 'Transtornos mentais e comportamentais devidos ao uso de cocaína' },
  { code: 'F15', name: 'Transtornos mentais e comportamentais devidos ao uso de estimulantes' },
  { code: 'F17', name: 'Transtornos mentais e comportamentais devidos ao uso de tabaco (tabagismo)' },
  { code: 'F19', name: 'Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas' },
  { code: 'F20', name: 'Esquizofrenia' },
  { code: 'F20.0', name: 'Esquizofrenia paranóide' },
  { code: 'F21', name: 'Transtorno esquizotípico' },
  { code: 'F22', name: 'Transtornos delirantes persistentes' },
  { code: 'F23', name: 'Transtornos psicóticos agudos e transitórios' },
  { code: 'F25', name: 'Transtornos esquizoafetivos' },
  { code: 'F29', name: 'Psicose não-orgânica não especificada' },
  { code: 'F30', name: 'Episódio maníaco' },
  { code: 'F31', name: 'Transtorno afetivo bipolar' },
  { code: 'F31.0', name: 'Transtorno afetivo bipolar, episódio atual hipomaníaco' },
  { code: 'F31.3', name: 'Transtorno afetivo bipolar, episódio atual depressivo leve ou moderado' },
  { code: 'F31.4', name: 'Transtorno afetivo bipolar, episódio atual depressivo grave sem sintomas psicóticos' },
  { code: 'F31.5', name: 'Transtorno afetivo bipolar, episódio atual depressivo grave com sintomas psicóticos' },
  { code: 'F32', name: 'Episódios depressivos' },
  { code: 'F32.0', name: 'Episódio depressivo leve' },
  { code: 'F32.1', name: 'Episódio depressivo moderado' },
  { code: 'F32.2', name: 'Episódio depressivo grave sem sintomas psicóticos' },
  { code: 'F32.3', name: 'Episódio depressivo grave com sintomas psicóticos' },
  { code: 'F32.9', name: 'Episódio depressivo não especificado' },
  { code: 'F33', name: 'Transtorno depressivo recorrente' },
  { code: 'F33.0', name: 'Transtorno depressivo recorrente, episódio atual leve' },
  { code: 'F33.1', name: 'Transtorno depressivo recorrente, episódio atual moderado' },
  { code: 'F33.2', name: 'Transtorno depressivo recorrente, episódio atual grave sem sintomas psicóticos' },
  { code: 'F34', name: 'Transtornos de humor (afetivos) persistentes' },
  { code: 'F34.1', name: 'Distimia' },
  { code: 'F40', name: 'Transtornos fóbico-ansiosos' },
  { code: 'F40.0', name: 'Agorafobia' },
  { code: 'F40.1', name: 'Fobias sociais' },
  { code: 'F40.2', name: 'Fobias específicas (isoladas)' },
  { code: 'F41', name: 'Outros transtornos ansiosos' },
  { code: 'F41.0', name: 'Transtorno de pânico (ansiedade paroxística episódica)' },
  { code: 'F41.1', name: 'Ansiedade generalizada' },
  { code: 'F41.2', name: 'Transtorno misto ansioso e depressivo' },
  { code: 'F41.9', name: 'Transtorno ansioso não especificado' },
  { code: 'F42', name: 'Transtorno obsessivo-compulsivo' },
  { code: 'F43', name: 'Reações ao estresse grave e transtornos de adaptação' },
  { code: 'F43.0', name: 'Reação aguda ao estresse' },
  { code: 'F43.1', name: 'Estado de estresse pós-traumático' },
  { code: 'F43.2', name: 'Transtornos de adaptação' },
  { code: 'F44', name: 'Transtornos dissociativos (de conversão)' },
  { code: 'F45', name: 'Transtornos somatoformes' },
  { code: 'F45.0', name: 'Transtorno de somatização' },
  { code: 'F48', name: 'Outros transtornos neuróticos' },
  { code: 'F50', name: 'Transtornos da alimentação' },
  { code: 'F50.0', name: 'Anorexia nervosa' },
  { code: 'F50.2', name: 'Bulimia nervosa' },
  { code: 'F51', name: 'Transtornos não-orgânicos do sono' },
  { code: 'F51.0', name: 'Insônia não-orgânica' },
  { code: 'F52', name: 'Disfunção sexual não causada por transtorno ou doença orgânica' },
  { code: 'F60', name: 'Transtornos específicos da personalidade' },
  { code: 'F60.3', name: 'Transtorno de personalidade emocionalmente instável (borderline)' },
  { code: 'F63', name: 'Transtornos dos hábitos e dos impulsos' },
  { code: 'F70', name: 'Retardo mental leve' },
  { code: 'F71', name: 'Retardo mental moderado' },
  { code: 'F79', name: 'Retardo mental não especificado' },
  { code: 'F80', name: 'Transtornos específicos do desenvolvimento da fala e da linguagem' },
  { code: 'F81', name: 'Transtornos específicos do desenvolvimento das habilidades escolares' },
  { code: 'F84', name: 'Transtornos globais do desenvolvimento' },
  { code: 'F84.0', name: 'Autismo infantil' },
  { code: 'F84.1', name: 'Autismo atípico' },
  { code: 'F84.5', name: 'Síndrome de Asperger' },
  { code: 'F90', name: 'Transtornos hipercinéticos (TDAH)' },
  { code: 'F90.0', name: 'Distúrbios da atividade e da atenção' },
  { code: 'F91', name: 'Distúrbios de conduta' },
  { code: 'F92', name: 'Transtornos mistos de conduta e das emoções' },
  { code: 'F93', name: 'Transtornos emocionais com início especificamente na infância' },
  { code: 'F98', name: 'Outros transtornos comportamentais e emocionais com início na infância e adolescência' },
  { code: 'F99', name: 'Transtorno mental não especificado' },

  // ===== G00-G99: Doenças do sistema nervoso =====
  { code: 'G00', name: 'Meningite bacteriana não classificada em outra parte' },
  { code: 'G03', name: 'Meningite devida a outras causas e a causas não especificadas' },
  { code: 'G04', name: 'Encefalite, mielite e encefalomielite' },
  { code: 'G06', name: 'Abscesso e granuloma intracranianos e intra-raquidianos' },
  { code: 'G10', name: 'Doença de Huntington' },
  { code: 'G20', name: 'Doença de Parkinson' },
  { code: 'G21', name: 'Parkinsonismo secundário' },
  { code: 'G24', name: 'Distonia' },
  { code: 'G25', name: 'Outras doenças extrapiramidais e transtornos dos movimentos' },
  { code: 'G25.0', name: 'Tremor essencial' },
  { code: 'G30', name: 'Doença de Alzheimer' },
  { code: 'G31', name: 'Outras doenças degenerativas do sistema nervoso' },
  { code: 'G35', name: 'Esclerose múltipla' },
  { code: 'G40', name: 'Epilepsia' },
  { code: 'G40.0', name: 'Epilepsia e síndromes epilépticas idiopáticas' },
  { code: 'G40.9', name: 'Epilepsia não especificada' },
  { code: 'G41', name: 'Estado de mal epiléptico' },
  { code: 'G43', name: 'Enxaqueca' },
  { code: 'G43.0', name: 'Enxaqueca sem aura (enxaqueca comum)' },
  { code: 'G43.1', name: 'Enxaqueca com aura (enxaqueca clássica)' },
  { code: 'G43.9', name: 'Enxaqueca sem especificação' },
  { code: 'G44', name: 'Outras síndromes de algias cefálicas' },
  { code: 'G44.2', name: 'Cefaléia tensional' },
  { code: 'G45', name: 'Acidentes vasculares cerebrais isquêmicos transitórios' },
  { code: 'G47', name: 'Distúrbios do sono' },
  { code: 'G47.3', name: 'Apnéia de sono' },
  { code: 'G50', name: 'Transtornos do nervo trigêmeo' },
  { code: 'G50.0', name: 'Neuralgia do trigêmeo' },
  { code: 'G51', name: 'Transtornos do nervo facial' },
  { code: 'G51.0', name: 'Paralisia de Bell (paralisia facial periférica)' },
  { code: 'G54', name: 'Transtornos das raízes e dos plexos nervosos' },
  { code: 'G56', name: 'Mononeuropatias do membro superior' },
  { code: 'G56.0', name: 'Síndrome do túnel do carpo' },
  { code: 'G57', name: 'Mononeuropatias do membro inferior' },
  { code: 'G58', name: 'Outras mononeuropatias' },
  { code: 'G61', name: 'Polineuropatia inflamatória' },
  { code: 'G61.0', name: 'Síndrome de Guillain-Barré' },
  { code: 'G62', name: 'Outras polineuropatias' },
  { code: 'G63', name: 'Polineuropatia em doenças classificadas em outra parte' },
  { code: 'G70', name: 'Miastenia gravis e outros transtornos neuromusculares' },
  { code: 'G71', name: 'Transtornos primários dos músculos (distrofias musculares)' },
  { code: 'G80', name: 'Paralisia cerebral' },
  { code: 'G81', name: 'Hemiplegia' },
  { code: 'G82', name: 'Paraplegia e tetraplegia' },
  { code: 'G83', name: 'Outras síndromes paralíticas' },
  { code: 'G89', name: 'Dor não classificada em outra parte' },
  { code: 'G91', name: 'Hidrocefalia' },
  { code: 'G93', name: 'Outros transtornos do encéfalo' },
  { code: 'G93.3', name: 'Síndrome da fadiga pós-viral (síndrome de fadiga crônica)' },

  // ===== H00-H59: Doenças do olho =====
  { code: 'H00', name: 'Hordéolo e calázio' },
  { code: 'H01', name: 'Outras inflamações da pálpebra' },
  { code: 'H04', name: 'Transtornos do aparelho lacrimal' },
  { code: 'H10', name: 'Conjuntivite' },
  { code: 'H10.0', name: 'Conjuntivite mucopurulenta' },
  { code: 'H10.1', name: 'Conjuntivite atópica aguda' },
  { code: 'H11', name: 'Outros transtornos da conjuntiva' },
  { code: 'H16', name: 'Ceratite' },
  { code: 'H20', name: 'Iridociclite' },
  { code: 'H25', name: 'Catarata senil' },
  { code: 'H26', name: 'Outras cataratas' },
  { code: 'H33', name: 'Descolamentos e defeitos da retina' },
  { code: 'H35', name: 'Outros transtornos da retina' },
  { code: 'H35.3', name: 'Degeneração da mácula e do pólo posterior' },
  { code: 'H36', name: 'Transtornos da retina em doenças classificadas em outra parte' },
  { code: 'H40', name: 'Glaucoma' },
  { code: 'H40.1', name: 'Glaucoma primário de ângulo aberto' },
  { code: 'H43', name: 'Transtornos do humor vítreo' },
  { code: 'H46', name: 'Neurite óptica' },
  { code: 'H47', name: 'Outros transtornos do nervo óptico e das vias ópticas' },
  { code: 'H49', name: 'Estrabismo paralítico' },
  { code: 'H50', name: 'Outros estrabismos' },
  { code: 'H52', name: 'Transtornos da refração e da acomodação' },
  { code: 'H52.0', name: 'Hipermetropia' },
  { code: 'H52.1', name: 'Miopia' },
  { code: 'H52.2', name: 'Astigmatismo' },
  { code: 'H52.4', name: 'Presbiopia' },
  { code: 'H53', name: 'Distúrbios visuais' },
  { code: 'H54', name: 'Cegueira e visão subnormal' },

  // ===== H60-H95: Doenças do ouvido =====
  { code: 'H60', name: 'Otite externa' },
  { code: 'H61', name: 'Outros transtornos do ouvido externo' },
  { code: 'H65', name: 'Otite média não-supurativa' },
  { code: 'H66', name: 'Otite média supurativa e as não especificadas' },
  { code: 'H66.9', name: 'Otite média não especificada' },
  { code: 'H70', name: 'Mastoidite e afecções relacionadas' },
  { code: 'H72', name: 'Perfuração da membrana do tímpano' },
  { code: 'H80', name: 'Otosclerose' },
  { code: 'H81', name: 'Transtornos da função vestibular' },
  { code: 'H81.0', name: 'Doença de Ménière' },
  { code: 'H81.1', name: 'Vertigem paroxística benigna' },
  { code: 'H81.3', name: 'Outras vertigens periféricas' },
  { code: 'H83', name: 'Outros transtornos do ouvido interno' },
  { code: 'H90', name: 'Perda de audição por transtorno de condução e/ou neurossensorial' },
  { code: 'H91', name: 'Outras perdas de audição' },
  { code: 'H91.1', name: 'Presbiacusia' },
  { code: 'H91.2', name: 'Perda de audição súbita idiopática' },
  { code: 'H93', name: 'Outros transtornos do ouvido' },
  { code: 'H93.1', name: 'Zumbido (tinido)' },

  // ===== I00-I99: Doenças do aparelho circulatório =====
  { code: 'I00', name: 'Febre reumática sem menção de comprometimento do coração' },
  { code: 'I05', name: 'Doenças reumáticas da valva mitral' },
  { code: 'I06', name: 'Doenças reumáticas da valva aórtica' },
  { code: 'I10', name: 'Hipertensão essencial (primária)' },
  { code: 'I11', name: 'Doença cardíaca hipertensiva' },
  { code: 'I12', name: 'Doença renal hipertensiva' },
  { code: 'I13', name: 'Doença cardíaca e renal hipertensiva' },
  { code: 'I15', name: 'Hipertensão secundária' },
  { code: 'I20', name: 'Angina pectoris' },
  { code: 'I20.0', name: 'Angina instável' },
  { code: 'I20.9', name: 'Angina pectoris não especificada' },
  { code: 'I21', name: 'Infarto agudo do miocárdio' },
  { code: 'I21.0', name: 'Infarto agudo transmural da parede anterior do miocárdio' },
  { code: 'I21.9', name: 'Infarto agudo do miocárdio não especificado' },
  { code: 'I22', name: 'Infarto do miocárdio recorrente' },
  { code: 'I24', name: 'Outras doenças isquêmicas agudas do coração' },
  { code: 'I25', name: 'Doença isquêmica crônica do coração' },
  { code: 'I25.1', name: 'Doença aterosclerótica do coração' },
  { code: 'I26', name: 'Embolia pulmonar' },
  { code: 'I27', name: 'Outras formas de doença cardíaca pulmonar' },
  { code: 'I27.0', name: 'Hipertensão pulmonar primária' },
  { code: 'I30', name: 'Pericardite aguda' },
  { code: 'I31', name: 'Outras doenças do pericárdio' },
  { code: 'I33', name: 'Endocardite aguda e subaguda' },
  { code: 'I34', name: 'Transtornos não-reumáticos da valva mitral' },
  { code: 'I34.1', name: 'Prolapso da valva mitral' },
  { code: 'I35', name: 'Transtornos não-reumáticos da valva aórtica' },
  { code: 'I35.0', name: 'Estenose (da valva) aórtica' },
  { code: 'I38', name: 'Endocardite de valva não especificada' },
  { code: 'I40', name: 'Miocardite aguda' },
  { code: 'I42', name: 'Cardiomiopatia' },
  { code: 'I42.0', name: 'Cardiomiopatia dilatada' },
  { code: 'I42.1', name: 'Cardiomiopatia obstrutiva hipertrófica' },
  { code: 'I44', name: 'Bloqueio atrioventricular e do ramo esquerdo' },
  { code: 'I45', name: 'Outros transtornos de condução' },
  { code: 'I46', name: 'Parada cardíaca' },
  { code: 'I47', name: 'Taquicardia paroxística' },
  { code: 'I47.1', name: 'Taquicardia supraventricular' },
  { code: 'I47.2', name: 'Taquicardia ventricular' },
  { code: 'I48', name: 'Flutter e fibrilação atrial' },
  { code: 'I49', name: 'Outras arritmias cardíacas' },
  { code: 'I49.5', name: 'Síndrome do nódulo sinusal' },
  { code: 'I50', name: 'Insuficiência cardíaca' },
  { code: 'I50.0', name: 'Insuficiência cardíaca congestiva' },
  { code: 'I50.1', name: 'Insuficiência ventricular esquerda' },
  { code: 'I50.9', name: 'Insuficiência cardíaca não especificada' },
  { code: 'I51', name: 'Complicações de cardiopatias e doenças cardíacas mal definidas' },
  { code: 'I60', name: 'Hemorragia subaracnóide' },
  { code: 'I61', name: 'Hemorragia intracerebral' },
  { code: 'I63', name: 'Infarto cerebral' },
  { code: 'I64', name: 'Acidente vascular cerebral, não especificado como hemorrágico ou isquêmico' },
  { code: 'I65', name: 'Oclusão e estenose de artérias pré-cerebrais que não resultam em infarto cerebral' },
  { code: 'I67', name: 'Outras doenças cerebrovasculares' },
  { code: 'I69', name: 'Seqüelas de doenças cerebrovasculares' },
  { code: 'I70', name: 'Aterosclerose' },
  { code: 'I71', name: 'Aneurisma e dissecção da aorta' },
  { code: 'I73', name: 'Outras doenças vasculares periféricas' },
  { code: 'I73.0', name: 'Síndrome de Raynaud' },
  { code: 'I73.9', name: 'Doença vascular periférica não especificada' },
  { code: 'I74', name: 'Embolia e trombose arteriais' },
  { code: 'I77', name: 'Outras afecções das artérias e arteríolas' },
  { code: 'I80', name: 'Flebite e tromboflebite' },
  { code: 'I80.2', name: 'Flebite e tromboflebite de outros vasos profundos dos membros inferiores (TVP)' },
  { code: 'I83', name: 'Varizes dos membros inferiores' },
  { code: 'I84', name: 'Hemorróidas' },
  { code: 'I85', name: 'Varizes esofágicas' },
  { code: 'I86', name: 'Varizes de outras localizações' },
  { code: 'I87', name: 'Outros transtornos das veias' },
  { code: 'I87.2', name: 'Insuficiência venosa (crônica) (periférica)' },
  { code: 'I89', name: 'Outros transtornos não-infecciosos dos vasos linfáticos e dos gânglios linfáticos' },
  { code: 'I95', name: 'Hipotensão' },
  { code: 'I95.1', name: 'Hipotensão ortostática' },

  // ===== J00-J99: Doenças do aparelho respiratório =====
  { code: 'J00', name: 'Nasofaringite aguda (resfriado comum)' },
  { code: 'J01', name: 'Sinusite aguda' },
  { code: 'J02', name: 'Faringite aguda' },
  { code: 'J03', name: 'Amigdalite aguda' },
  { code: 'J04', name: 'Laringite e traqueíte agudas' },
  { code: 'J05', name: 'Laringite obstrutiva aguda (crupe) e epiglotite' },
  { code: 'J06', name: 'Infecções agudas das vias aéreas superiores de localizações múltiplas e não especificadas' },
  { code: 'J06.9', name: 'Infecção aguda das vias aéreas superiores não especificada' },
  { code: 'J09', name: 'Influenza (gripe) devida a vírus identificado da gripe aviária' },
  { code: 'J10', name: 'Influenza (gripe) devida a outro vírus da influenza identificado' },
  { code: 'J11', name: 'Influenza (gripe) devida a vírus não identificado' },
  { code: 'J12', name: 'Pneumonia viral não classificada em outra parte' },
  { code: 'J13', name: 'Pneumonia devida a Streptococcus pneumoniae' },
  { code: 'J14', name: 'Pneumonia devida a Haemophilus infuenzae' },
  { code: 'J15', name: 'Pneumonia bacteriana não classificada em outra parte' },
  { code: 'J18', name: 'Pneumonia por microorganismo não especificada' },
  { code: 'J18.9', name: 'Pneumonia não especificada' },
  { code: 'J20', name: 'Bronquite aguda' },
  { code: 'J21', name: 'Bronquiolite aguda' },
  { code: 'J22', name: 'Infecção aguda não especificada das vias aéreas inferiores' },
  { code: 'J30', name: 'Rinite alérgica e vasomotora' },
  { code: 'J30.1', name: 'Rinite alérgica devida a pólen' },
  { code: 'J30.3', name: 'Outras rinites alérgicas (rinite alérgica perene)' },
  { code: 'J30.4', name: 'Rinite alérgica não especificada' },
  { code: 'J31', name: 'Rinite, nasofaringite e faringite crônicas' },
  { code: 'J32', name: 'Sinusite crônica' },
  { code: 'J33', name: 'Pólipo nasal' },
  { code: 'J34', name: 'Outros transtornos do nariz e dos seios paranasais' },
  { code: 'J34.2', name: 'Desvio do septo nasal' },
  { code: 'J35', name: 'Doenças crônicas das amígdalas e das adenóides' },
  { code: 'J35.0', name: 'Amigdalite crônica' },
  { code: 'J37', name: 'Laringite e laringotraqueíte crônicas' },
  { code: 'J38', name: 'Doenças das cordas vocais e da laringe' },
  { code: 'J39', name: 'Outras doenças das vias aéreas superiores' },
  { code: 'J40', name: 'Bronquite não especificada como aguda ou crônica' },
  { code: 'J41', name: 'Bronquite crônica simples e a mucopurulenta' },
  { code: 'J42', name: 'Bronquite crônica não especificada' },
  { code: 'J43', name: 'Enfisema' },
  { code: 'J44', name: 'Outras doenças pulmonares obstrutivas crônicas (DPOC)' },
  { code: 'J44.0', name: 'Doença pulmonar obstrutiva crônica com infecção respiratória aguda do trato inferior' },
  { code: 'J44.1', name: 'Doença pulmonar obstrutiva crônica com exacerbação aguda' },
  { code: 'J44.8', name: 'Outras formas especificadas de doença pulmonar obstrutiva crônica' },
  { code: 'J45', name: 'Asma' },
  { code: 'J45.0', name: 'Asma predominantemente alérgica' },
  { code: 'J45.1', name: 'Asma não-alérgica' },
  { code: 'J45.9', name: 'Asma não especificada' },
  { code: 'J46', name: 'Estado de mal asmático (asma aguda grave)' },
  { code: 'J47', name: 'Bronquiectasia' },
  { code: 'J60', name: 'Pneumoconiose dos mineiros de carvão' },
  { code: 'J61', name: 'Pneumoconiose devida a asbesto (amianto) e outras fibras minerais' },
  { code: 'J67', name: 'Pneumonite de hipersensibilidade devida a poeiras orgânicas' },
  { code: 'J68', name: 'Afecções respiratórias devidas a inalação de produtos químicos, gases, fumaças e vapores' },
  { code: 'J69', name: 'Pneumonite devida a sólidos e líquidos' },
  { code: 'J80', name: 'Síndrome do desconforto respiratório do adulto (SDRA)' },
  { code: 'J81', name: 'Edema pulmonar' },
  { code: 'J84', name: 'Outras doenças pulmonares intersticiais' },
  { code: 'J84.1', name: 'Outras doenças pulmonares intersticiais com fibrose' },
  { code: 'J85', name: 'Abscesso do pulmão e do mediastino' },
  { code: 'J86', name: 'Empiema' },
  { code: 'J90', name: 'Derrame pleural não classificado em outra parte' },
  { code: 'J93', name: 'Pneumotórax' },
  { code: 'J96', name: 'Insuficiência respiratória não classificada em outra parte' },
  { code: 'J96.0', name: 'Insuficiência respiratória aguda' },
  { code: 'J96.1', name: 'Insuficiência respiratória crônica' },
  { code: 'J98', name: 'Outros transtornos respiratórios' },

  // ===== K00-K93: Doenças do aparelho digestivo =====
  { code: 'K00', name: 'Distúrbios do desenvolvimento e da erupção dos dentes' },
  { code: 'K01', name: 'Dentes inclusos e impactados' },
  { code: 'K02', name: 'Cárie dentária' },
  { code: 'K04', name: 'Doenças da polpa e dos tecidos periapicais' },
  { code: 'K05', name: 'Gengivite e doenças periodontais' },
  { code: 'K08', name: 'Outros transtornos dos dentes e das estruturas de sustentação' },
  { code: 'K10', name: 'Outras doenças dos maxilares' },
  { code: 'K11', name: 'Doenças das glândulas salivares' },
  { code: 'K12', name: 'Estomatite e lesões afins' },
  { code: 'K13', name: 'Outras doenças do lábio e da mucosa oral' },
  { code: 'K14', name: 'Doenças da língua' },
  { code: 'K20', name: 'Esofagite' },
  { code: 'K21', name: 'Doença de refluxo gastroesofágico (DRGE)' },
  { code: 'K21.0', name: 'Doença de refluxo gastroesofágico com esofagite' },
  { code: 'K22', name: 'Outras doenças do esôfago' },
  { code: 'K25', name: 'Úlcera gástrica' },
  { code: 'K26', name: 'Úlcera duodenal' },
  { code: 'K27', name: 'Úlcera péptica de localização não especificada' },
  { code: 'K29', name: 'Gastrite e duodenite' },
  { code: 'K29.7', name: 'Gastrite não especificada' },
  { code: 'K30', name: 'Dispepsia' },
  { code: 'K31', name: 'Outras doenças do estômago e do duodeno' },
  { code: 'K35', name: 'Apendicite aguda' },
  { code: 'K36', name: 'Outras formas de apendicite' },
  { code: 'K37', name: 'Apendicite sem outras especificações' },
  { code: 'K40', name: 'Hérnia inguinal' },
  { code: 'K41', name: 'Hérnia femoral (crural)' },
  { code: 'K42', name: 'Hérnia umbilical' },
  { code: 'K43', name: 'Hérnia ventral' },
  { code: 'K44', name: 'Hérnia diafragmática' },
  { code: 'K46', name: 'Hérnia abdominal não especificada' },
  { code: 'K50', name: 'Doença de Crohn (enterite regional)' },
  { code: 'K51', name: 'Colite ulcerativa' },
  { code: 'K52', name: 'Outras gastroenterites e colites não-infecciosas' },
  { code: 'K55', name: 'Transtornos vasculares do intestino' },
  { code: 'K56', name: 'Íleo paralítico e obstrução intestinal sem hérnia' },
  { code: 'K57', name: 'Doença diverticular do intestino' },
  { code: 'K58', name: 'Síndrome do intestino irritável' },
  { code: 'K58.0', name: 'Síndrome do intestino irritável com diarreia' },
  { code: 'K58.9', name: 'Síndrome do intestino irritável sem diarreia' },
  { code: 'K59', name: 'Outros transtornos funcionais do intestino' },
  { code: 'K59.0', name: 'Constipação' },
  { code: 'K60', name: 'Fissura e fístula das regiões anal e retal' },
  { code: 'K61', name: 'Abscesso das regiões anal e retal' },
  { code: 'K62', name: 'Outras doenças do reto e do ânus' },
  { code: 'K63', name: 'Outras doenças do intestino' },
  { code: 'K65', name: 'Peritonite' },
  { code: 'K70', name: 'Doença alcoólica do fígado' },
  { code: 'K71', name: 'Doença hepática tóxica' },
  { code: 'K72', name: 'Insuficiência hepática não classificada em outra parte' },
  { code: 'K73', name: 'Hepatite crônica não classificada em outra parte' },
  { code: 'K74', name: 'Fibrose e cirrose hepáticas' },
  { code: 'K75', name: 'Outras doenças inflamatórias do fígado' },
  { code: 'K76', name: 'Outras doenças do fígado' },
  { code: 'K76.0', name: 'Degeneração gordurosa do fígado (esteatose hepática)' },
  { code: 'K80', name: 'Colelitíase (cálculos biliares)' },
  { code: 'K81', name: 'Colecistite' },
  { code: 'K82', name: 'Outras doenças da vesícula biliar' },
  { code: 'K83', name: 'Outras doenças das vias biliares' },
  { code: 'K85', name: 'Pancreatite aguda' },
  { code: 'K86', name: 'Outras doenças do pâncreas' },
  { code: 'K86.1', name: 'Outras formas de pancreatite crônica' },
  { code: 'K90', name: 'Má-absorção intestinal' },
  { code: 'K90.0', name: 'Doença celíaca' },
  { code: 'K92', name: 'Outras doenças do aparelho digestivo' },
  { code: 'K92.0', name: 'Hematêmese' },
  { code: 'K92.1', name: 'Melena' },
  { code: 'K92.2', name: 'Hemorragia gastrointestinal não especificada' },

  // ===== L00-L99: Doenças da pele e tecido subcutâneo =====
  { code: 'L00', name: 'Síndrome da pele escaldada estafilocócica do recém-nascido' },
  { code: 'L01', name: 'Impetigo' },
  { code: 'L02', name: 'Abscesso cutâneo, furúnculo e carbúnculo' },
  { code: 'L03', name: 'Celulite' },
  { code: 'L04', name: 'Linfadenite aguda' },
  { code: 'L05', name: 'Cisto pilonidal' },
  { code: 'L08', name: 'Outras infecções locais da pele e do tecido subcutâneo' },
  { code: 'L10', name: 'Pênfigo' },
  { code: 'L12', name: 'Penfigóide' },
  { code: 'L13', name: 'Outras afecções bolhosas' },
  { code: 'L20', name: 'Dermatite atópica' },
  { code: 'L21', name: 'Dermatite seborréica' },
  { code: 'L22', name: 'Dermatite das fraldas' },
  { code: 'L23', name: 'Dermatite alérgica de contato' },
  { code: 'L24', name: 'Dermatite de contato por irritantes' },
  { code: 'L25', name: 'Dermatite de contato não especificada' },
  { code: 'L27', name: 'Dermatite devida a substâncias de uso interno' },
  { code: 'L28', name: 'Líquen simples crônico e prurigo' },
  { code: 'L29', name: 'Prurido' },
  { code: 'L30', name: 'Outras dermatites' },
  { code: 'L30.9', name: 'Dermatite não especificada (eczema)' },
  { code: 'L40', name: 'Psoríase' },
  { code: 'L40.0', name: 'Psoríase vulgar' },
  { code: 'L42', name: 'Pitiríase rósea' },
  { code: 'L43', name: 'Líquen plano' },
  { code: 'L50', name: 'Urticária' },
  { code: 'L50.0', name: 'Urticária alérgica' },
  { code: 'L50.1', name: 'Urticária idiopática' },
  { code: 'L51', name: 'Eritema multiforme' },
  { code: 'L53', name: 'Outras afecções eritematosas' },
  { code: 'L55', name: 'Queimadura solar' },
  { code: 'L56', name: 'Outras alterações agudas da pele devidas a radiação ultravioleta' },
  { code: 'L57', name: 'Alterações da pele devidas à exposição crônica à radiação não-ionizante' },
  { code: 'L60', name: 'Afecções das unhas' },
  { code: 'L63', name: 'Alopecia areata' },
  { code: 'L64', name: 'Alopecia androgenética' },
  { code: 'L65', name: 'Outra perda de cabelo ou pêlos não-cicatricial' },
  { code: 'L70', name: 'Acne' },
  { code: 'L70.0', name: 'Acne vulgar' },
  { code: 'L71', name: 'Rosácea' },
  { code: 'L72', name: 'Cistos foliculares da pele e do tecido subcutâneo' },
  { code: 'L73', name: 'Outras afecções foliculares' },
  { code: 'L80', name: 'Vitiligo' },
  { code: 'L81', name: 'Outros transtornos da pigmentação' },
  { code: 'L82', name: 'Ceratose seborréica' },
  { code: 'L84', name: 'Calos e calosidades' },
  { code: 'L85', name: 'Outros espessamentos da pele' },
  { code: 'L90', name: 'Afecções atróficas da pele' },
  { code: 'L91', name: 'Afecções hipertróficas da pele' },
  { code: 'L91.0', name: 'Cicatriz quelóide' },
  { code: 'L97', name: 'Úlcera dos membros inferiores não classificada em outra parte' },
  { code: 'L98', name: 'Outras afecções da pele e do tecido subcutâneo' },

  // ===== M00-M99: Doenças do sistema osteomuscular e tecido conjuntivo =====
  { code: 'M00', name: 'Artrite piogênica' },
  { code: 'M05', name: 'Artrite reumatóide soropositiva' },
  { code: 'M06', name: 'Outras artrites reumatóides' },
  { code: 'M06.9', name: 'Artrite reumatóide não especificada' },
  { code: 'M10', name: 'Gota' },
  { code: 'M10.0', name: 'Gota idiopática' },
  { code: 'M10.9', name: 'Gota não especificada' },
  { code: 'M13', name: 'Outras artrites' },
  { code: 'M13.9', name: 'Artrite não especificada' },
  { code: 'M15', name: 'Poliartrose' },
  { code: 'M16', name: 'Coxartrose (artrose do quadril)' },
  { code: 'M17', name: 'Gonartrose (artrose do joelho)' },
  { code: 'M19', name: 'Outras artroses' },
  { code: 'M19.9', name: 'Artrose não especificada' },
  { code: 'M20', name: 'Deformidades adquiridas dos dedos das mãos e dos pés' },
  { code: 'M21', name: 'Outras deformidades adquiridas dos membros' },
  { code: 'M22', name: 'Transtornos da rótula (patela)' },
  { code: 'M23', name: 'Transtornos internos dos joelhos' },
  { code: 'M24', name: 'Outros transtornos articulares específicos' },
  { code: 'M25', name: 'Outros transtornos articulares não classificados em outra parte' },
  { code: 'M25.5', name: 'Dor articular' },
  { code: 'M30', name: 'Poliarterite nodosa e afecções correlatas' },
  { code: 'M31', name: 'Outras vasculopatias necrotizantes' },
  { code: 'M32', name: 'Lúpus eritematoso disseminado (sistêmico)' },
  { code: 'M33', name: 'Dermatopolimiosite' },
  { code: 'M34', name: 'Esclerose sistêmica (esclerodermia)' },
  { code: 'M35', name: 'Outras doenças sistêmicas do tecido conjuntivo' },
  { code: 'M35.3', name: 'Polimialgia reumática' },
  { code: 'M40', name: 'Cifose e lordose' },
  { code: 'M41', name: 'Escoliose' },
  { code: 'M42', name: 'Osteocondrose da coluna vertebral' },
  { code: 'M43', name: 'Outras dorsopatias deformantes' },
  { code: 'M45', name: 'Espondilite anquilosante' },
  { code: 'M46', name: 'Outras espondilopatias inflamatórias' },
  { code: 'M47', name: 'Espondilose' },
  { code: 'M48', name: 'Outras espondilopatias' },
  { code: 'M48.0', name: 'Estenose da coluna vertebral' },
  { code: 'M50', name: 'Transtornos dos discos cervicais' },
  { code: 'M51', name: 'Outros transtornos de discos intervertebrais' },
  { code: 'M51.1', name: 'Transtornos de discos lombares com radiculopatia' },
  { code: 'M53', name: 'Outras dorsopatias não classificadas em outra parte' },
  { code: 'M54', name: 'Dorsalgia' },
  { code: 'M54.1', name: 'Radiculopatia' },
  { code: 'M54.2', name: 'Cervicalgia' },
  { code: 'M54.3', name: 'Ciática' },
  { code: 'M54.4', name: 'Lumbago com ciática' },
  { code: 'M54.5', name: 'Dor lombar baixa (lombalgia)' },
  { code: 'M54.6', name: 'Dor na coluna torácica' },
  { code: 'M54.9', name: 'Dorsalgia não especificada' },
  { code: 'M60', name: 'Miosite' },
  { code: 'M62', name: 'Outros transtornos musculares' },
  { code: 'M65', name: 'Sinovite e tenossinovite' },
  { code: 'M65.4', name: 'Tenossinovite do estiloide radial (De Quervain)' },
  { code: 'M67', name: 'Outros transtornos das sinóvias e dos tendões' },
  { code: 'M70', name: 'Transtornos dos tecidos moles relacionados ao uso, uso excessivo e pressão' },
  { code: 'M71', name: 'Outras bursopatias' },
  { code: 'M72', name: 'Transtornos fibroblásticos' },
  { code: 'M72.0', name: 'Fibromatose da fáscia palmar (Dupuytren)' },
  { code: 'M75', name: 'Lesões do ombro' },
  { code: 'M75.0', name: 'Capsulite adesiva do ombro (ombro congelado)' },
  { code: 'M75.1', name: 'Síndrome do manguito rotador' },
  { code: 'M75.3', name: 'Tendinite calcificada do ombro' },
  { code: 'M76', name: 'Entesopatias dos membros inferiores excluindo o pé' },
  { code: 'M77', name: 'Outras entesopatias' },
  { code: 'M77.0', name: 'Epicondilite medial' },
  { code: 'M77.1', name: 'Epicondilite lateral (cotovelo de tenista)' },
  { code: 'M77.3', name: 'Esporão de calcâneo' },
  { code: 'M77.5', name: 'Outra entesopatia do pé' },
  { code: 'M79', name: 'Outros transtornos de tecidos moles, não classificados em outra parte' },
  { code: 'M79.1', name: 'Mialgia' },
  { code: 'M79.3', name: 'Paniculite não especificada' },
  { code: 'M79.7', name: 'Fibromialgia' },
  { code: 'M80', name: 'Osteoporose com fratura patológica' },
  { code: 'M81', name: 'Osteoporose sem fratura patológica' },
  { code: 'M81.0', name: 'Osteoporose pós-menopáusica' },
  { code: 'M81.9', name: 'Osteoporose não especificada' },
  { code: 'M84', name: 'Transtornos da continuidade do osso' },
  { code: 'M84.1', name: 'Pseudoartrose' },
  { code: 'M85', name: 'Outros transtornos da densidade e da estrutura ósseas' },
  { code: 'M86', name: 'Osteomielite' },
  { code: 'M87', name: 'Osteonecrose' },

  // ===== N00-N99: Doenças do aparelho geniturinário =====
  { code: 'N00', name: 'Síndrome nefrítica aguda' },
  { code: 'N02', name: 'Hematúria recidivante e persistente' },
  { code: 'N03', name: 'Síndrome nefrítica crônica' },
  { code: 'N04', name: 'Síndrome nefrótica' },
  { code: 'N05', name: 'Síndrome nefrítica não especificada' },
  { code: 'N10', name: 'Nefrite túbulo-intersticial aguda (pielonefrite aguda)' },
  { code: 'N11', name: 'Nefrite túbulo-intersticial crônica' },
  { code: 'N12', name: 'Nefrite túbulo-intersticial não especificada como aguda ou crônica' },
  { code: 'N13', name: 'Uropatia obstrutiva e de refluxo' },
  { code: 'N17', name: 'Insuficiência renal aguda' },
  { code: 'N18', name: 'Insuficiência renal crônica (doença renal crônica)' },
  { code: 'N18.1', name: 'Doença renal crônica, estádio 1' },
  { code: 'N18.2', name: 'Doença renal crônica, estádio 2' },
  { code: 'N18.3', name: 'Doença renal crônica, estádio 3' },
  { code: 'N18.4', name: 'Doença renal crônica, estádio 4' },
  { code: 'N18.5', name: 'Doença renal crônica, estádio 5' },
  { code: 'N18.9', name: 'Insuficiência renal crônica não especificada' },
  { code: 'N19', name: 'Insuficiência renal não especificada' },
  { code: 'N20', name: 'Calculose do rim e do ureter (litíase renal)' },
  { code: 'N20.0', name: 'Cálculo do rim (nefrolitíase)' },
  { code: 'N20.1', name: 'Cálculo do ureter' },
  { code: 'N21', name: 'Calculose do trato urinário inferior' },
  { code: 'N23', name: 'Cólica renal não especificada' },
  { code: 'N28', name: 'Outros transtornos do rim e do ureter' },
  { code: 'N30', name: 'Cistite' },
  { code: 'N30.0', name: 'Cistite aguda' },
  { code: 'N30.1', name: 'Cistite intersticial crônica' },
  { code: 'N34', name: 'Uretrite e síndrome uretral' },
  { code: 'N39', name: 'Outros transtornos do trato urinário' },
  { code: 'N39.0', name: 'Infecção do trato urinário de localização não especificada' },
  { code: 'N39.3', name: 'Incontinência urinária de esforço' },
  { code: 'N39.4', name: 'Outras incontinências urinárias especificadas' },
  { code: 'N40', name: 'Hiperplasia da próstata' },
  { code: 'N41', name: 'Doenças inflamatórias da próstata' },
  { code: 'N41.0', name: 'Prostatite aguda' },
  { code: 'N41.1', name: 'Prostatite crônica' },
  { code: 'N42', name: 'Outros transtornos da próstata' },
  { code: 'N43', name: 'Hidrocele e espermatocele' },
  { code: 'N44', name: 'Torção do testículo' },
  { code: 'N45', name: 'Orquite e epididimite' },
  { code: 'N46', name: 'Infertilidade masculina' },
  { code: 'N47', name: 'Prepúcio redundante, fimose e parafimose' },
  { code: 'N48', name: 'Outros transtornos do pênis' },
  { code: 'N49', name: 'Transtornos inflamatórios de órgãos genitais masculinos' },
  { code: 'N60', name: 'Displasia mamária benigna' },
  { code: 'N61', name: 'Transtornos inflamatórios da mama' },
  { code: 'N62', name: 'Hipertrofia da mama' },
  { code: 'N63', name: 'Nódulo mamário não especificado' },
  { code: 'N64', name: 'Outros transtornos da mama' },
  { code: 'N70', name: 'Salpingite e ooforite' },
  { code: 'N71', name: 'Doença inflamatória do útero, exceto o colo' },
  { code: 'N72', name: 'Doença inflamatória do colo do útero (cervicite)' },
  { code: 'N73', name: 'Outras doenças inflamatórias pélvicas femininas' },
  { code: 'N75', name: 'Doenças da glândula de Bartholin' },
  { code: 'N76', name: 'Outras afecções inflamatórias da vagina e da vulva' },
  { code: 'N76.0', name: 'Vaginite aguda' },
  { code: 'N77', name: 'Ulceração e inflamação vulvovaginal em doenças classificadas em outra parte' },
  { code: 'N80', name: 'Endometriose' },
  { code: 'N81', name: 'Prolapso genital feminino' },
  { code: 'N83', name: 'Transtornos não-inflamatórios do ovário, da trompa de Falópio e do ligamento largo' },
  { code: 'N83.0', name: 'Cisto folicular do ovário' },
  { code: 'N84', name: 'Pólipo do trato genital feminino' },
  { code: 'N85', name: 'Outros transtornos não-inflamatórios do útero, excluído o colo' },
  { code: 'N87', name: 'Displasia do colo do útero' },
  { code: 'N89', name: 'Outros transtornos não-inflamatórios da vagina' },
  { code: 'N91', name: 'Menstruação ausente, escassa e reduzida' },
  { code: 'N92', name: 'Menstruação excessiva, freqüente e irregular' },
  { code: 'N93', name: 'Outros sangramentos anormais do útero e da vagina' },
  { code: 'N94', name: 'Dor e outras afecções associadas com os órgãos genitais femininos e com o ciclo menstrual' },
  { code: 'N94.6', name: 'Dismenorréia não especificada' },
  { code: 'N95', name: 'Transtornos da menopausa e do climatério' },
  { code: 'N95.1', name: 'Estados da menopausa e do climatério feminino' },
  { code: 'N97', name: 'Infertilidade feminina' },

  // ===== O00-O99: Gravidez, parto e puerpério =====
  { code: 'O00', name: 'Gravidez ectópica' },
  { code: 'O01', name: 'Mola hidatiforme' },
  { code: 'O02', name: 'Outros produtos anormais da concepção' },
  { code: 'O03', name: 'Aborto espontâneo' },
  { code: 'O04', name: 'Aborto por razões médicas' },
  { code: 'O06', name: 'Aborto não especificado' },
  { code: 'O10', name: 'Hipertensão pré-existente complicando a gravidez, o parto e o puerpério' },
  { code: 'O11', name: 'Distúrbio hipertensivo pré-existente com proteinúria superposta' },
  { code: 'O12', name: 'Edema e proteinúria gestacionais' },
  { code: 'O13', name: 'Hipertensão gestacional sem proteinúria significativa' },
  { code: 'O14', name: 'Hipertensão gestacional com proteinúria significativa (pré-eclâmpsia)' },
  { code: 'O15', name: 'Eclâmpsia' },
  { code: 'O20', name: 'Hemorragia do início da gravidez' },
  { code: 'O21', name: 'Vômitos excessivos na gravidez' },
  { code: 'O23', name: 'Infecções do trato geniturinário na gravidez' },
  { code: 'O24', name: 'Diabetes mellitus na gravidez' },
  { code: 'O24.4', name: 'Diabetes mellitus gestacional' },
  { code: 'O26', name: 'Assistência materna por outras complicações da gravidez' },
  { code: 'O28', name: 'Achados anormais no exame pré-natal da mãe' },
  { code: 'O30', name: 'Gestação múltipla' },
  { code: 'O32', name: 'Assistência prestada à mãe por motivo conhecido ou suspeito de apresentação anormal do feto' },
  { code: 'O34', name: 'Assistência prestada à mãe por anormalidade dos órgãos pélvicos' },
  { code: 'O36', name: 'Assistência prestada à mãe por outros problemas fetais' },
  { code: 'O42', name: 'Ruptura prematura de membranas' },
  { code: 'O44', name: 'Placenta prévia' },
  { code: 'O45', name: 'Descolamento prematuro da placenta' },
  { code: 'O46', name: 'Hemorragia anteparto' },
  { code: 'O47', name: 'Falso trabalho de parto' },
  { code: 'O48', name: 'Gravidez prolongada' },
  { code: 'O60', name: 'Trabalho de parto pré-termo' },
  { code: 'O62', name: 'Anormalidades da contração uterina' },
  { code: 'O63', name: 'Trabalho de parto prolongado' },
  { code: 'O64', name: 'Obstrução do trabalho de parto devida à má-posição ou má-apresentação do feto' },
  { code: 'O68', name: 'Trabalho de parto e parto complicados por sofrimento fetal' },
  { code: 'O69', name: 'Trabalho de parto e parto complicados por anormalidade do cordão umbilical' },
  { code: 'O70', name: 'Laceração do períneo durante o parto' },
  { code: 'O72', name: 'Hemorragia pós-parto' },
  { code: 'O80', name: 'Parto único espontâneo' },
  { code: 'O82', name: 'Parto único por cesariana' },
  { code: 'O85', name: 'Infecção puerperal' },
  { code: 'O86', name: 'Outras infecções puerperais' },
  { code: 'O90', name: 'Complicações do puerpério não classificadas em outra parte' },
  { code: 'O91', name: 'Infecções da mama associadas ao parto' },
  { code: 'O92', name: 'Outras afecções da mama e da lactação associadas ao parto' },
  { code: 'O99', name: 'Outras doenças da mãe classificadas em outra parte, mas que complicam a gravidez, parto e puerpério' },

  // ===== P00-P96: Afecções originadas no período perinatal =====
  { code: 'P05', name: 'Crescimento fetal retardado e desnutrição fetal' },
  { code: 'P07', name: 'Transtornos relacionados com a gestação curta e peso baixo ao nascer' },
  { code: 'P08', name: 'Transtornos relacionados com a gestação prolongada e peso elevado ao nascer' },
  { code: 'P21', name: 'Asfixia ao nascer' },
  { code: 'P22', name: 'Desconforto respiratório do recém-nascido' },
  { code: 'P23', name: 'Pneumonia congênita' },
  { code: 'P28', name: 'Outras afecções respiratórias originadas no período perinatal' },
  { code: 'P35', name: 'Doenças virais congênitas' },
  { code: 'P36', name: 'Septicemia bacteriana do recém-nascido' },
  { code: 'P38', name: 'Onfalite do recém-nascido' },
  { code: 'P59', name: 'Icterícia neonatal devida a outras causas e às não especificadas' },
  { code: 'P61', name: 'Outros transtornos hematológicos perinatais' },
  { code: 'P70', name: 'Transtornos transitórios do metabolismo dos carboidratos específicos do feto e do recém-nascido' },
  { code: 'P74', name: 'Outros distúrbios eletrolíticos e metabólicos transitórios do período neonatal' },
  { code: 'P90', name: 'Convulsões do recém-nascido' },
  { code: 'P91', name: 'Outras perturbações da função cerebral do recém-nascido' },
  { code: 'P96', name: 'Outras afecções originadas no período perinatal' },

  // ===== Q00-Q99: Malformações congênitas =====
  { code: 'Q00', name: 'Anencefalia e malformações similares' },
  { code: 'Q01', name: 'Encefalocele' },
  { code: 'Q02', name: 'Microcefalia' },
  { code: 'Q03', name: 'Hidrocefalia congênita' },
  { code: 'Q04', name: 'Outras malformações congênitas do cérebro' },
  { code: 'Q05', name: 'Espinha bífida' },
  { code: 'Q10', name: 'Malformações congênitas das pálpebras, do aparelho lacrimal e da órbita' },
  { code: 'Q17', name: 'Outras malformações congênitas da orelha' },
  { code: 'Q20', name: 'Malformações congênitas das câmaras cardíacas e das comunicações' },
  { code: 'Q21', name: 'Malformações congênitas dos septos cardíacos' },
  { code: 'Q21.0', name: 'Comunicação interventricular (CIV)' },
  { code: 'Q21.1', name: 'Comunicação interatrial (CIA)' },
  { code: 'Q23', name: 'Malformações congênitas das valvas aórtica e mitral' },
  { code: 'Q24', name: 'Outras malformações congênitas do coração' },
  { code: 'Q25', name: 'Malformações congênitas das grandes artérias' },
  { code: 'Q25.0', name: 'Persistência do canal arterial' },
  { code: 'Q25.1', name: 'Coarctação da aorta' },
  { code: 'Q35', name: 'Fenda palatina' },
  { code: 'Q36', name: 'Fenda labial' },
  { code: 'Q37', name: 'Fenda labial com fenda palatina' },
  { code: 'Q39', name: 'Malformações congênitas do esôfago' },
  { code: 'Q40', name: 'Outras malformações congênitas do trato alimentar superior' },
  { code: 'Q42', name: 'Ausência, atresia e estenose congênita do intestino grosso' },
  { code: 'Q43', name: 'Outras malformações congênitas do intestino' },
  { code: 'Q53', name: 'Testículo não-descido (criptorquidia)' },
  { code: 'Q54', name: 'Hipospádias' },
  { code: 'Q56', name: 'Sexo indeterminado e pseudo-hermafroditismo' },
  { code: 'Q60', name: 'Agenesia renal e outros defeitos de redução do rim' },
  { code: 'Q61', name: 'Doenças císticas do rim' },
  { code: 'Q62', name: 'Defeitos obstrutivos congênitos da pelve renal e malformações congênitas do ureter' },
  { code: 'Q65', name: 'Malformações congênitas do quadril' },
  { code: 'Q66', name: 'Deformidades congênitas do pé' },
  { code: 'Q66.0', name: 'Pé torto congênito (talipes equinovarus)' },
  { code: 'Q67', name: 'Deformidades osteomusculares congênitas da cabeça, face, coluna e tórax' },
  { code: 'Q69', name: 'Polidactilia' },
  { code: 'Q70', name: 'Sindactilia' },
  { code: 'Q71', name: 'Defeitos de redução do membro superior' },
  { code: 'Q79', name: 'Malformações congênitas do sistema osteomuscular' },
  { code: 'Q82', name: 'Outras malformações congênitas da pele' },
  { code: 'Q85', name: 'Facomatoses não classificadas em outra parte' },
  { code: 'Q86', name: 'Síndromes com malformações congênitas devidas a causas exógenas conhecidas' },
  { code: 'Q87', name: 'Outras síndromes com malformações congênitas que acometem múltiplos sistemas' },
  { code: 'Q90', name: 'Síndrome de Down' },
  { code: 'Q91', name: 'Síndrome de Edwards e síndrome de Patau' },
  { code: 'Q96', name: 'Síndrome de Turner' },
  { code: 'Q98', name: 'Outras anomalias dos cromossomos sexuais' },
  { code: 'Q99', name: 'Outras anomalias dos cromossomos' },

  // ===== R00-R99: Sintomas, sinais e achados anormais =====
  { code: 'R00', name: 'Anormalidades do batimento cardíaco' },
  { code: 'R00.0', name: 'Taquicardia não especificada' },
  { code: 'R00.1', name: 'Bradicardia não especificada' },
  { code: 'R00.2', name: 'Palpitações' },
  { code: 'R01', name: 'Sopros e outros sons cardíacos' },
  { code: 'R03', name: 'Valores anormais de pressão arterial sem diagnóstico' },
  { code: 'R04', name: 'Hemorragia das vias respiratórias' },
  { code: 'R04.0', name: 'Epistaxe (sangramento nasal)' },
  { code: 'R04.2', name: 'Hemoptise' },
  { code: 'R05', name: 'Tosse' },
  { code: 'R06', name: 'Anormalidades da respiração' },
  { code: 'R06.0', name: 'Dispnéia' },
  { code: 'R06.2', name: 'Sibilância' },
  { code: 'R07', name: 'Dor de garganta e no peito' },
  { code: 'R07.3', name: 'Outras dores torácicas (dor torácica anterior)' },
  { code: 'R07.4', name: 'Dor torácica não especificada' },
  { code: 'R09', name: 'Outros sintomas e sinais relativos aos aparelhos circulatório e respiratório' },
  { code: 'R10', name: 'Dor abdominal e pélvica' },
  { code: 'R10.0', name: 'Abdome agudo' },
  { code: 'R10.1', name: 'Dor localizada no abdome superior' },
  { code: 'R10.3', name: 'Dor localizada em outras partes inferiores do abdome' },
  { code: 'R10.4', name: 'Outras dores abdominais e as não especificadas' },
  { code: 'R11', name: 'Náusea e vômitos' },
  { code: 'R12', name: 'Pirose' },
  { code: 'R13', name: 'Disfagia' },
  { code: 'R14', name: 'Flatulência e afecções correlatas' },
  { code: 'R15', name: 'Incontinência fecal' },
  { code: 'R16', name: 'Hepatomegalia e esplenomegalia' },
  { code: 'R17', name: 'Icterícia não especificada' },
  { code: 'R18', name: 'Ascite' },
  { code: 'R19', name: 'Outros sintomas e sinais relativos ao aparelho digestivo e ao abdome' },
  { code: 'R20', name: 'Distúrbios da sensibilidade cutânea' },
  { code: 'R21', name: 'Eritema e outras erupções cutâneas não especificadas' },
  { code: 'R22', name: 'Tumefação, massa ou tumoração localizadas da pele e do tecido subcutâneo' },
  { code: 'R23', name: 'Outras alterações cutâneas' },
  { code: 'R25', name: 'Movimentos involuntários anormais' },
  { code: 'R26', name: 'Anormalidades da marcha e da mobilidade' },
  { code: 'R27', name: 'Outros distúrbios da coordenação' },
  { code: 'R29', name: 'Outros sintomas e sinais relativos aos sistemas nervoso e osteomuscular' },
  { code: 'R30', name: 'Dor associada à micção' },
  { code: 'R31', name: 'Hematúria não especificada' },
  { code: 'R32', name: 'Incontinência urinária não especificada' },
  { code: 'R33', name: 'Retenção urinária' },
  { code: 'R35', name: 'Poliúria' },
  { code: 'R39', name: 'Outros sintomas e sinais relativos ao aparelho urinário' },
  { code: 'R40', name: 'Sonolência, estupor e coma' },
  { code: 'R41', name: 'Outros sintomas e sinais relativos à função cognitiva e à consciência' },
  { code: 'R42', name: 'Tontura e instabilidade' },
  { code: 'R44', name: 'Outros sintomas e sinais relativos às sensações e às percepções gerais' },
  { code: 'R45', name: 'Sintomas e sinais relativos ao estado emocional' },
  { code: 'R46', name: 'Sintomas e sinais relativos à aparência e ao comportamento' },
  { code: 'R47', name: 'Distúrbios da fala não classificados em outra parte' },
  { code: 'R49', name: 'Distúrbios da voz' },
  { code: 'R50', name: 'Febre de origem desconhecida' },
  { code: 'R50.9', name: 'Febre não especificada' },
  { code: 'R51', name: 'Cefaléia' },
  { code: 'R52', name: 'Dor não classificada em outra parte' },
  { code: 'R53', name: 'Mal-estar e fadiga' },
  { code: 'R55', name: 'Síncope e colapso' },
  { code: 'R56', name: 'Convulsões não classificadas em outra parte' },
  { code: 'R57', name: 'Choque não classificado em outra parte' },
  { code: 'R58', name: 'Hemorragia não classificada em outra parte' },
  { code: 'R59', name: 'Aumento de volume dos gânglios linfáticos' },
  { code: 'R60', name: 'Edema não classificado em outra parte' },
  { code: 'R62', name: 'Retardo do desenvolvimento fisiológico normal' },
  { code: 'R63', name: 'Sintomas e sinais relativos à alimentação e à ingestão de líquidos' },
  { code: 'R63.0', name: 'Anorexia' },
  { code: 'R63.4', name: 'Perda de peso anormal' },
  { code: 'R63.5', name: 'Ganho de peso anormal' },
  { code: 'R68', name: 'Outros sintomas e sinais gerais' },
  { code: 'R69', name: 'Causas desconhecidas e não especificadas de morbidade' },
  { code: 'R73', name: 'Valores elevados da glicemia' },
  { code: 'R73.0', name: 'Teste de tolerância à glicose anormal' },
  { code: 'R73.9', name: 'Hiperglicemia não especificada' },
  { code: 'R74', name: 'Valores anormais de transaminases e de enzimas hepáticas' },
  { code: 'R76', name: 'Outros achados imunológicos anormais no soro' },
  { code: 'R79', name: 'Outros achados anormais de exames químicos do sangue' },
  { code: 'R80', name: 'Proteinúria isolada' },
  { code: 'R82', name: 'Outros achados anormais na urina' },
  { code: 'R87', name: 'Achados anormais nos materiais de procedência dos órgãos genitais femininos' },
  { code: 'R91', name: 'Achados anormais em exames de diagnóstico por imagem do pulmão' },
  { code: 'R94', name: 'Resultados anormais de estudos de função' },

  // ===== S00-T98: Lesões, envenenamentos e conseqüências de causas externas =====
  { code: 'S00', name: 'Traumatismo superficial da cabeça' },
  { code: 'S01', name: 'Ferimento da cabeça' },
  { code: 'S02', name: 'Fratura do crânio e dos ossos da face' },
  { code: 'S06', name: 'Traumatismo intracraniano' },
  { code: 'S06.0', name: 'Concussão cerebral' },
  { code: 'S09', name: 'Outros traumatismos da cabeça e os não especificados' },
  { code: 'S12', name: 'Fratura do pescoço' },
  { code: 'S13', name: 'Luxação, entorse e distensão das articulações e dos ligamentos do pescoço' },
  { code: 'S14', name: 'Traumatismo de nervos e da medula espinhal ao nível cervical' },
  { code: 'S22', name: 'Fratura de costela(s), do esterno e da coluna torácica' },
  { code: 'S32', name: 'Fratura da coluna lombar e da pelve' },
  { code: 'S42', name: 'Fratura do ombro e do braço' },
  { code: 'S43', name: 'Luxação, entorse e distensão das articulações e dos ligamentos da cintura escapular' },
  { code: 'S46', name: 'Traumatismo de tendões e músculos ao nível do ombro e do braço' },
  { code: 'S49', name: 'Outros traumatismos do ombro e do braço e os não especificados' },
  { code: 'S50', name: 'Traumatismo superficial do antebraço' },
  { code: 'S52', name: 'Fratura do antebraço' },
  { code: 'S53', name: 'Luxação, entorse e distensão das articulações e dos ligamentos do cotovelo' },
  { code: 'S60', name: 'Traumatismo superficial do punho e da mão' },
  { code: 'S61', name: 'Ferimento do punho e da mão' },
  { code: 'S62', name: 'Fratura ao nível do punho e da mão' },
  { code: 'S63', name: 'Luxação, entorse e distensão das articulações e dos ligamentos ao nível do punho e da mão' },
  { code: 'S72', name: 'Fratura do fêmur' },
  { code: 'S73', name: 'Luxação, entorse e distensão da articulação e dos ligamentos do quadril' },
  { code: 'S80', name: 'Traumatismo superficial da perna' },
  { code: 'S82', name: 'Fratura da perna, incluindo tornozelo' },
  { code: 'S83', name: 'Luxação, entorse e distensão das articulações e dos ligamentos do joelho' },
  { code: 'S83.0', name: 'Luxação da rótula' },
  { code: 'S83.1', name: 'Luxação do joelho' },
  { code: 'S83.2', name: 'Ruptura do menisco, atual' },
  { code: 'S83.4', name: 'Entorse e distensão envolvendo ligamento colateral (do joelho)' },
  { code: 'S83.5', name: 'Entorse e distensão envolvendo ligamento cruzado do joelho' },
  { code: 'S86', name: 'Traumatismo de tendões e músculos ao nível da perna' },
  { code: 'S90', name: 'Traumatismo superficial do tornozelo e do pé' },
  { code: 'S92', name: 'Fratura do pé (exceto do tornozelo)' },
  { code: 'S93', name: 'Luxação, entorse e distensão das articulações e dos ligamentos ao nível do tornozelo e do pé' },
  { code: 'T07', name: 'Traumatismos múltiplos não especificados' },
  { code: 'T14', name: 'Traumatismo de região não especificada do corpo' },
  { code: 'T15', name: 'Corpo estranho na parte externa do olho' },
  { code: 'T17', name: 'Corpo estranho no trato respiratório' },
  { code: 'T18', name: 'Corpo estranho no aparelho digestivo' },
  { code: 'T20', name: 'Queimadura e corrosão da cabeça e pescoço' },
  { code: 'T21', name: 'Queimadura e corrosão do tronco' },
  { code: 'T22', name: 'Queimadura e corrosão do ombro e membro superior' },
  { code: 'T23', name: 'Queimadura e corrosão do punho e da mão' },
  { code: 'T24', name: 'Queimadura e corrosão do quadril e membro inferior' },
  { code: 'T30', name: 'Queimadura e corrosão de parte não especificada do corpo' },
  { code: 'T36', name: 'Intoxicação por antibióticos sistêmicos' },
  { code: 'T39', name: 'Intoxicação por analgésicos não-opiáceos, antipiréticos e anti-reumáticos' },
  { code: 'T40', name: 'Intoxicação por narcóticos e psicodislépticos (alucinógenos)' },
  { code: 'T42', name: 'Intoxicação por antiepilépticos, sedativo-hipnóticos e antiparkinsonianos' },
  { code: 'T43', name: 'Intoxicação por drogas psicotrópicas' },
  { code: 'T50', name: 'Intoxicação por diuréticos e outras drogas, medicamentos e substâncias biológicas' },
  { code: 'T51', name: 'Efeito tóxico do álcool' },
  { code: 'T58', name: 'Efeito tóxico do monóxido de carbono' },
  { code: 'T63', name: 'Efeito tóxico do contato com animais venenosos' },
  { code: 'T65', name: 'Efeito tóxico de outras substâncias e das não especificadas' },
  { code: 'T68', name: 'Hipotermia' },
  { code: 'T71', name: 'Asfixia' },
  { code: 'T75', name: 'Efeitos de outras causas externas' },
  { code: 'T78', name: 'Efeitos adversos não classificados em outra parte' },
  { code: 'T78.0', name: 'Choque anafilático devido a reação adversa a alimento' },
  { code: 'T78.1', name: 'Outras manifestações de reação adversa a alimentos' },
  { code: 'T78.2', name: 'Choque anafilático não especificado' },
  { code: 'T78.3', name: 'Angioedema' },
  { code: 'T78.4', name: 'Alergia não especificada' },
  { code: 'T79', name: 'Algumas complicações precoces de traumatismos' },
  { code: 'T81', name: 'Complicações de procedimentos não classificadas em outra parte' },
  { code: 'T84', name: 'Complicações de dispositivos protéticos, implantes e enxertos ortopédicos internos' },
  { code: 'T88', name: 'Outras complicações de cuidados médicos e cirúrgicos' },

  // ===== Z00-Z99: Fatores que influenciam o estado de saúde e o contato com serviços de saúde =====
  { code: 'Z00', name: 'Exame geral e investigação de pessoas sem queixas ou diagnóstico relatado' },
  { code: 'Z00.0', name: 'Exame médico geral (check-up)' },
  { code: 'Z00.1', name: 'Exame de rotina da criança' },
  { code: 'Z01', name: 'Outros exames especiais e investigações de pessoas sem queixa ou diagnóstico' },
  { code: 'Z01.0', name: 'Exame dos olhos e da visão' },
  { code: 'Z01.1', name: 'Exame dos ouvidos e da audição' },
  { code: 'Z01.2', name: 'Exame dentário' },
  { code: 'Z01.4', name: 'Exame ginecológico' },
  { code: 'Z02', name: 'Exame e encontro para fins administrativos' },
  { code: 'Z03', name: 'Observação e avaliação médica por doenças e afecções suspeitas' },
  { code: 'Z04', name: 'Exame e observação por outras razões' },
  { code: 'Z09', name: 'Exame de seguimento após tratamento por outras afecções além de neoplasias malignas' },
  { code: 'Z10', name: 'Exame geral de rotina de uma subpopulação definida' },
  { code: 'Z11', name: 'Exame especial de rastreamento de doenças infecciosas e parasitárias' },
  { code: 'Z12', name: 'Exame especial de rastreamento de neoplasias' },
  { code: 'Z13', name: 'Exame especial de rastreamento de outras doenças e transtornos' },
  { code: 'Z20', name: 'Contato com e exposição a doenças transmissíveis' },
  { code: 'Z21', name: 'Estado de infecção assintomática pelo vírus da imunodeficiência humana (HIV)' },
  { code: 'Z22', name: 'Portador de doença infecciosa' },
  { code: 'Z23', name: 'Necessidade de imunização contra doenças bacterianas isoladas' },
  { code: 'Z24', name: 'Necessidade de imunização contra certas doenças virais' },
  { code: 'Z25', name: 'Necessidade de imunização contra outras doenças virais isoladas' },
  { code: 'Z26', name: 'Necessidade de imunização contra outras doenças infecciosas isoladas' },
  { code: 'Z27', name: 'Necessidade de imunização contra combinações de doenças infecciosas' },
  { code: 'Z29', name: 'Necessidade de outras medidas profiláticas' },
  { code: 'Z30', name: 'Anticoncepção' },
  { code: 'Z31', name: 'Medidas de procriação' },
  { code: 'Z32', name: 'Exame e teste de gravidez' },
  { code: 'Z33', name: 'Gravidez confirmada' },
  { code: 'Z34', name: 'Supervisão de gravidez normal' },
  { code: 'Z35', name: 'Supervisão de gravidez de alto risco' },
  { code: 'Z36', name: 'Rastreamento pré-natal' },
  { code: 'Z37', name: 'Resultado do parto' },
  { code: 'Z38', name: 'Nascidos vivos segundo o local de nascimento' },
  { code: 'Z39', name: 'Assistência e exame pós-natal' },
  { code: 'Z46', name: 'Colocação e ajustamento de outros aparelhos' },
  { code: 'Z47', name: 'Outros cuidados de seguimento ortopédico' },
  { code: 'Z48', name: 'Outros cuidados de seguimento cirúrgico' },
  { code: 'Z49', name: 'Cuidados envolvendo diálise' },
  { code: 'Z50', name: 'Cuidados envolvendo o uso de procedimentos de reabilitação' },
  { code: 'Z51', name: 'Outros cuidados médicos' },
  { code: 'Z51.0', name: 'Sessão de radioterapia' },
  { code: 'Z51.1', name: 'Sessão de quimioterapia por neoplasia' },
  { code: 'Z53', name: 'Pessoas em contato com serviços de saúde para procedimentos específicos, não realizados' },
  { code: 'Z54', name: 'Convalescença' },
  { code: 'Z55', name: 'Problemas relacionados com a educação e com a alfabetização' },
  { code: 'Z56', name: 'Problemas relacionados com o emprego e com o desemprego' },
  { code: 'Z57', name: 'Exposição ocupacional a fatores de risco' },
  { code: 'Z59', name: 'Problemas relacionados com a habitação e com as condições econômicas' },
  { code: 'Z60', name: 'Problemas relacionados com o meio social' },
  { code: 'Z61', name: 'Problemas relacionados com eventos negativos de vida na infância' },
  { code: 'Z62', name: 'Outros problemas relacionados com a educação da criança' },
  { code: 'Z63', name: 'Outros problemas relacionados com o grupo primário de apoio, inclusive com a situação familiar' },
  { code: 'Z65', name: 'Problemas relacionados com outras circunstâncias psicossociais' },
  { code: 'Z71', name: 'Pessoas em contato com os serviços de saúde para outros aconselhamentos e consultas' },
  { code: 'Z72', name: 'Problemas relacionados com o estilo de vida' },
  { code: 'Z73', name: 'Problemas relacionados com a organização do modo de vida' },
  { code: 'Z73.0', name: 'Esgotamento (burnout, síndrome do esgotamento profissional)' },
  { code: 'Z74', name: 'Problemas relacionados com a dependência de prestador de serviços de saúde' },
  { code: 'Z76', name: 'Pessoas em contato com os serviços de saúde em outras circunstâncias' },
  { code: 'Z80', name: 'História familiar de neoplasia maligna' },
  { code: 'Z82', name: 'História familiar de certas incapacidades e doenças crônicas' },
  { code: 'Z83', name: 'História familiar de outros transtornos específicos' },
  { code: 'Z85', name: 'História pessoal de neoplasia maligna' },
  { code: 'Z86', name: 'História pessoal de algumas outras doenças' },
  { code: 'Z87', name: 'História pessoal de outras doenças e afecções' },
  { code: 'Z88', name: 'História pessoal de alergia a drogas, medicamentos e substâncias biológicas' },
  { code: 'Z90', name: 'Ausência adquirida de órgãos' },
  { code: 'Z91', name: 'História pessoal de fatores de risco, não classificados em outra parte' },
  { code: 'Z92', name: 'História pessoal de tratamento médico' },
  { code: 'Z93', name: 'Orifícios artificiais' },
  { code: 'Z94', name: 'Órgãos e tecidos transplantados' },
  { code: 'Z95', name: 'Presença de implantes e enxertos cardíacos e vasculares' },
  { code: 'Z96', name: 'Presença de outros implantes funcionais' },
  { code: 'Z97', name: 'Presença de outros dispositivos' },
  { code: 'Z98', name: 'Outros estados pós-cirúrgicos' },
  { code: 'Z99', name: 'Dependência de máquinas e dispositivos capacitantes' },
];

// Pre-compute normalized search index
interface CID10SearchEntry {
  code: string;
  name: string;
  normalizedCode: string;
  normalizedName: string;
}

let searchIndex: CID10SearchEntry[] | null = null;

function getSearchIndex(): CID10SearchEntry[] {
  if (!searchIndex) {
    searchIndex = CID10_DATABASE.map((entry) => ({
      code: entry.code,
      name: entry.name,
      normalizedCode: normalizeForSearch(entry.code),
      normalizedName: normalizeForSearch(entry.name),
    }));
  }
  return searchIndex;
}

export interface CID10SearchResult {
  code: string;
  name: string;
  /** Label for display: "CODE - Name" */
  label: string;
}

/**
 * Search CID-10 codes by code or name (PT-BR).
 * Supports searching by code prefix (e.g., "E11") or by name (e.g., "diabetes").
 * Accent-insensitive and case-insensitive.
 */
export function searchCID10(query: string, limit = 20): CID10SearchResult[] {
  if (!query || query.trim().length === 0) {
    return [];
  }

  const normalizedQuery = normalizeForSearch(query.trim());
  const index = getSearchIndex();

  const results: Array<CID10SearchEntry & { score: number }> = [];

  for (const entry of index) {
    let score = 0;

    // Exact code match (highest priority)
    if (entry.normalizedCode === normalizedQuery) {
      score = 100;
    }
    // Code starts with query
    else if (entry.normalizedCode.startsWith(normalizedQuery)) {
      score = 80;
    }
    // Code contains query
    else if (entry.normalizedCode.includes(normalizedQuery)) {
      score = 60;
    }
    // Name starts with query
    else if (entry.normalizedName.startsWith(normalizedQuery)) {
      score = 50;
    }
    // Name contains query (word boundary)
    else if (entry.normalizedName.includes(` ${normalizedQuery}`)) {
      score = 40;
    }
    // Name contains query anywhere
    else if (entry.normalizedName.includes(normalizedQuery)) {
      score = 30;
    }
    // Multi-word search: all terms must match
    else if (normalizedQuery.includes(' ')) {
      const terms = normalizedQuery.split(/\s+/);
      const allMatch = terms.every(
        (term) => entry.normalizedCode.includes(term) || entry.normalizedName.includes(term)
      );
      if (allMatch) {
        score = 25;
      }
    }

    if (score > 0) {
      results.push({ ...entry, score });
    }
  }

  // Sort by score descending, then by code length (shorter = more specific), then alphabetically
  results.sort((a, b) => {
    if (b.score !== a.score) return b.score - a.score;
    if (a.code.length !== b.code.length) return a.code.length - b.code.length;
    return a.code.localeCompare(b.code);
  });

  return results.slice(0, limit).map((r) => ({
    code: r.code,
    name: r.name,
    label: `${r.code} - ${r.name}`,
  }));
}

/** Get total number of CID-10 codes in the database */
export function getCID10Count(): number {
  return CID10_DATABASE.length;
}
